name: smoke-test
on:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]

jobs:
  run:
    runs-on: ubuntu-latest
    if: "!github.event.pull_request.draft"
    steps:
    - name: "🚀 Deploy QA"
      run: "echo Deploying ${{ github.head_ref }} to QA for ${{ github.actor }}"
